[theme]

# Primary accent for interactive elements
primaryColor = '#E98074'

# Background color for the main content area
backgroundColor = '#EAE7DC'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#D8C3A5'

# Color used for almost all text
textColor = '#E85A4F'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
