[theme]

# Primary accent for interactive elements
primaryColor = '#D65A31'

# Background color for the main content area
backgroundColor = '#222831'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#393E46'

# Color used for almost all text
textColor = '#EEEEEE'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
