[theme]

# Primary accent for interactive elements
primaryColor = '#F1B4BB'

# Background color for the main content area
backgroundColor = '#132043'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1F4172'

# Color used for almost all text
textColor = '#FDF0F0'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
